### ISSUE TITLE
Conversion to avif produces a larger file than the original if the quality setting is above 40.

### ISSUE THREAD

**Issue by newissuemaker** [gen2brain/cbconvert#43]
I used to compress my comics by converting them to avif with lancsoz filter at 100, doing so would produce tiny files with little impact on quality. 

I've looked at the past issues and apparently the quality slider didn't work for avif in the past and also imagemagick has been dropped, hence the difference in behavior now. What settings should I use to get the results I got before the changes?

**Comment by gen2brain** [comment]
Quality 100 is, as I noticed in other formats, always a special case, some formats will enable lossless and ignore quality, and some will not allow you to use many options if you choose 100%. Everything is different. I don't really want to support all that and don't have time for whatever wishes people have, sorry, but it is what it is. You can use 99% and be done with that, or contribute, I don't plan to spend much time with this project, I only do what I need as a user.

**Comment by gen2brain** [comment]
Also, you may want to try JPEG, now it uses `jpegli` instead of standard libjpeg, for a dozen comics I save about 100M, with the same settings, and the same everything, it is just smaller and universally supported. And I have tens of thousands of comics. 
Whatever is happening for AVIF format, it is done with `libavif`, and I don't want to go there and debug `libavif` issues.

**Comment by newissuemaker** [comment]
That's alright, thank you for replying. I tried just using jpeg as you said and found it saved a ton of space.
